# Generated by Django 4.1.1 on 2022-10-23 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('Options', 'GameOptions'),
        migrations.RenameModel('UserChoices', 'UserGameChoices'),
    ]
