# Generated by Django 4.1.1 on 2022-11-19 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_leaguestandings_user_alter_gameoptions_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaguestandings',
            name='user',
        ),
        migrations.AlterField(
            model_name='leaguestandings',
            name='user_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
    ]
