# Generated by Django 4.1.1 on 2022-12-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_leaguestandings_user_alter_gameoptions_condition_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leaguestandings',
            name='unique user entry per league',
        ),
        migrations.AddField(
            model_name='gameoptions',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='leaguestandings',
            constraint=models.UniqueConstraint(fields=('league', 'user'), name='unique user entry per league'),
        ),
    ]
