# Generated by Django 4.1.1 on 2022-11-13 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_alter_game_deleted_at_alter_gameoptions_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usergamechoices',
            name='unique choices',
        ),
        migrations.RemoveField(
            model_name='leaguestandings',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usergamechoices',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='usergamechoices',
            name='position',
        ),
        migrations.AddField(
            model_name='leaguestandings',
            name='user_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergamechoices',
            name='pos1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos1', to='bingo.gameoptions'),
        ),
        migrations.AddField(
            model_name='usergamechoices',
            name='pos10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos10', to='bingo.gameoptions'),
        ),
        migrations.AddField(
            model_name='usergamechoices',
            name='pos11',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos11', to='bingo.gameoptions'),
        ),
        migrations.AddField(
            model_name='usergamechoices',
            name='pos12',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos12', to='bingo.gameoptions'),
        ),
        migrations.AddField(
            model_name='usergamechoices',
            name='pos13',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos13', to='bingo.gameoptions'),
        ),
        migrations.AddField(
            model_name='usergamechoices',
            name='pos14',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos14', to='bingo.gameoptions'),
        ),
        migrations.AddField(
            model_name='usergamechoices',
            name='pos15',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos15', to='bingo.gameoptions'),
        ),
        migrations.AddField(
            model_name='usergamechoices',
            name='pos16',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos16', to='bingo.gameoptions'),
        ),
        migrations.AddField(
            model_name='usergamechoices',
            name='pos17',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos17', to='bingo.gameoptions'),
        ),
        migrations.AddField(
            model_name='usergamechoices',
            name='pos18',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos18', to='bingo.gameoptions'),
        ),
        migrations.AddField(
            model_name='usergamechoices',
            name='pos19',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos19', to='bingo.gameoptions'),
        ),
        migrations.AddField(
            model_name='usergamechoices',
            name='pos2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos2', to='bingo.gameoptions'),
        ),
        migrations.AddField(
            model_name='usergamechoices',
            name='pos20',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos20', to='bingo.gameoptions'),
        ),
        migrations.AddField(
            model_name='usergamechoices',
            name='pos21',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos21', to='bingo.gameoptions'),
        ),
        migrations.AddField(
            model_name='usergamechoices',
            name='pos22',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos22', to='bingo.gameoptions'),
        ),
        migrations.AddField(
            model_name='usergamechoices',
            name='pos23',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos23', to='bingo.gameoptions'),
        ),
        migrations.AddField(
            model_name='usergamechoices',
            name='pos24',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos24', to='bingo.gameoptions'),
        ),
        migrations.AddField(
            model_name='usergamechoices',
            name='pos25',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos25', to='bingo.gameoptions'),
        ),
        migrations.AddField(
            model_name='usergamechoices',
            name='pos3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos3', to='bingo.gameoptions'),
        ),
        migrations.AddField(
            model_name='usergamechoices',
            name='pos4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos4', to='bingo.gameoptions'),
        ),
        migrations.AddField(
            model_name='usergamechoices',
            name='pos5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos5', to='bingo.gameoptions'),
        ),
        migrations.AddField(
            model_name='usergamechoices',
            name='pos6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos6', to='bingo.gameoptions'),
        ),
        migrations.AddField(
            model_name='usergamechoices',
            name='pos7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos7', to='bingo.gameoptions'),
        ),
        migrations.AddField(
            model_name='usergamechoices',
            name='pos8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos8', to='bingo.gameoptions'),
        ),
        migrations.AddField(
            model_name='usergamechoices',
            name='pos9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos9', to='bingo.gameoptions'),
        ),
        migrations.AlterField(
            model_name='usergamechoices',
            name='user_game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='bingo.usergame'),
        ),
    ]
