# Generated by Django 4.1.1 on 2023-01-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_remove_leaguestandings_unique user entry per league_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
