# Generated by Django 4.1.1 on 2022-11-19 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_remove_leaguestandings_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguestandings',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaguestandings',
            name='user_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
