# Generated by Django 4.1.1 on 2023-01-13 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0004_league_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='main_league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bingo.league'),
        ),
    ]
