# Generated by Django 4.1.1 on 2023-01-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0005_game_main_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='games',
            field=models.ManyToManyField(blank=True, to='bingo.game'),
        ),
    ]
